<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\Identities\Nine.Identities.Domain.Contracts\Nine.Identities.Domain.Contracts.csproj" />
      <ProjectReference Include="..\..\Nine.SharedKernel\Nine.SharedKernel.csproj" />
    </ItemGroup>

</Project>
