@WebApi_HostAddress = http://localhost:5029

POST {{WebApi_HostAddress}}/api/v1/AccountsWebApi
Content-Type: application/json

{
  "emailAddress": "jane@example.com",
  "password": "Password1!",
  "phoneNumber": "+123456789"
}

###
